name: '[ðŸš€] Deploy Project'
run-name: '[ðŸš€] Deploy Project on `${{ inputs.branch }}`'

on:
    workflow_call:
        inputs:
            branch:
                required: true
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: '[ðŸš€] Deploy'
        steps:
            - name: '[ðŸ±] Install apt packages'
              run: sudo apt-get install -y unzip rsync

            - name: '[â¬‡ï¸] Download artifact'
              uses: actions/download-artifact@v3
              with:
                  name: LSSM_V4-${{ github.sha }}

            - name: '[ðŸ“¦ï¸] Unzip artifact'
              run: |
                  unzip dist.zip -d ${{ github.workspace }}/dist
                  rm dist.zip

            - name: '[â„¹ï¸] list content of dist'
              run: ls -la dist

            - name: '[ðŸ—ï¸] Install SSH Key'
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_DEPLOY_KEY }}
                  known_hosts: 'placeholder to avoid errors'
                  if_key_exists: replace

            - name: '[ðŸ’¡] Adding Known Hosts'
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: '[ðŸš€] Deployment'
              if: ${{ success() }}
              # -h => human-readable output format for numbers
              # -i => itemize changes
              # -r => recursive
              # -t => preserve modification times
              # -u => update (skip files that are newer on the receiver)
              # -z => compress for transfer
              # --delete --delete-delay => delete files on server that are not in the local directory (in an efficient way)
              # --stats => show stats at the end
              # --progress => show progress during transfer
              # -e => specify ssh port
              run: rsync -hirtuz --delete --delete-delay --stats --progress -e "ssh -p 22" ./dist/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}/${{ inputs.branch }}

            - name: '[ðŸ”—] Create symlinks on server'
              if: ${{ success() }}
              run: |
                  ssh -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
                    ln -sf ${{ secrets.DEPLOY_DIR }}/static/.check_request.php ${{ secrets.DEPLOY_DIR }}/${{ inputs.branch }}/static/;
                    ln -sf ${{ secrets.DEPLOY_DIR }}/static/db_access.php ${{ secrets.DEPLOY_DIR }}/${{ inputs.branch }}/static/;
                    ln -sf ${{ secrets.DEPLOY_DIR }}/static/missions ${{ secrets.DEPLOY_DIR }}/${{ inputs.branch }}/static/;
                    ln -sf ${{ secrets.DEPLOY_DIR }}/static/releasenotes ${{ secrets.DEPLOY_DIR }}/${{ inputs.branch }}/static/;
                  "